### ISSUE TITLE
Not getting Desired Output

### ISSUE THREAD

**Issue by shivamwane** [EMAZIZ/DFNet_TF3#2]
I am facing the same problem you face not getting desired output so if you know solution to problem please help me

**Comment by EMAZIZ** [comment]
please elaborate @shivamwane

**Comment by shivamwane** [comment]
sir i am facing the same problem not getting proper image that u are facing
due to sample image sizes

**Comment by shivamwane** [comment]
why running test.py  i was getting an error 

Model C:/Users/sohail/DFNet_TF2/trainer/ckpt loaded.
Img:  C:/Users/sohail/DFNet_TF2/samples/celeba/img
Mask:  C:/Users/sohail/DFNet_TF2/samples/celeba/mask
Traceback (most recent call last):
  File "test.py", line 248, in <module>
    tester.inpaint(args.output, args.img, args.mask, merge_result=args.merge)
  File "test.py", line 201, in inpaint
    'img and mask should be both file or directory.')
NotImplementedError: img and mask should be both file or directory.

**Comment by shivamwane** [comment]
please update me

**Comment by shivamwane** [comment]
Please update @EMAZIZ

**Comment by EMAZIZ** [comment]
either you have the wrong path defined or your files are missing @shivamwane
